### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/scribble.rs#136]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c888d]

goroutine 735372 [running]:
github.com/scribble-rs/scribble.rs/game.roundTimerTicker(0xc0011d82c0)
        /root/scribble.rs/game/lobby.go:517 +0x7d
created by github.com/scribble-rs/scribble.rs/game.advanceLobby
        /root/scribble.rs/game/lobby.go:483 +0x38b

**Comment by Bios-Marcel** [comment]
Assuming this happened at https://github.com/scribble-rs/scribble.rs/blob/cf36d62353f9141ee80503eb593dace205604eee/game/lobby.go#L517 or alter, it probably means the lobby was nil.

**Comment by Bios-Marcel** [comment]
As this hasn't surfaced recently and I can't make sense of it, I'll be closing this.

**Comment by Bios-Marcel** [comment]
Might've been fixed with the develop merge: https://github.com/scribble-rs/scribble.rs/commit/64caed1a2df08cb738fc469fbf1a41f1ce80ec7d
